[package]
name = "quickmenu"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.9", package = "gtk4", features = ["v4_10"] }
gdk = { version = "0.9", package = "gdk4" }
gio = "0.20"
glib = "0.20"
tokio = { version = "1.0", features = ["process"] }
